{
 "title": "Web3Signer Eth2 Overview",
 "description": "Web3signer Eth2 Dashboard https://github.com/ConsenSys/web3signer",
 "tags": [
  "ethereum",
  "web3signer",
  "eth2.0"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "system", "query": "signing_signers_loaded_count" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Loaded keys",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "signing_signers_loaded_count{instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}"
    }
   ]
  },
  {
   "title": "Max heap",
   "type": "stat",
   "description": "The maximum heap setting of the node's JVM.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}"
    }
   ]
  },
  { "title": "Signing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Signing Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "signing_bls_signing_duration{instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Signatures/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(signing_bls_signing_duration_count{instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}[1m]))",
     "legendFormat": "sigs/s"
    }
   ]
  },
  {
   "title": "Slashing protection prevented Signings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(eth2_slashingprotection_prevented_signings{instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}[1m])"
    }
   ]
  },
  {
   "title": "Signings for unknown validators/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(signing_bls_missing_identifier_count{instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}[1m])"
    }
   ]
  },
  {
   "title": "Malformed Signing Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_bls_malformed_request_count{instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}[1m])"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Number of CPU cores in use.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}[1m])",
     "legendFormat": "CPU Time IRate [{{instance}}]"
    }
   ]
  },
  {
   "title": "JVM Heap Space",
   "type": "graph",
   "description": "Total amount of heap memory in use, and the amount allocated.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"web3signer.web3signer-gnosis.dappnode:9091\", area=\"heap\"} + ignoring(area) jvm_memory_bytes_used{instance=\"web3signer.web3signer-gnosis.dappnode:9091\", area=\"nonheap\"}",
     "legendFormat": "Heap used  [{{instance}}]"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=\"web3signer.web3signer-gnosis.dappnode:9091\", area=\"heap\"} + ignoring(area) jvm_memory_bytes_max{instance=\"web3signer.web3signer-gnosis.dappnode:9091\", area=\"nonheap\"}",
     "legendFormat": "Max heap [{{instance}}]"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "graph",
   "description": "The total system memory used by the process, otherwise known as the resident set size (RSS).",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}",
     "legendFormat": "RSS [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "description": "Percentage of time spent in garbage collection, young and old generation.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "description": "Threads allocated by the JVM.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"WAITING\",instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}",
     "legendFormat": "{{state}} [{{instance}}]"
    },
    {
     "expr": "jvm_threads_state{state=\"TIMED_WAITING\",instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}",
     "legendFormat": "{{state}} [{{instance}}]"
    },
    {
     "expr": "jvm_threads_state{state=\"RUNNABLE\",instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}",
     "legendFormat": "{{state}} [{{instance}}]"
    },
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\",instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}",
     "legendFormat": "{{state}} [{{instance}}]"
    },
    {
     "expr": "jvm_threads_state{state=\"NEW\",instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}",
     "legendFormat": "{{state}} [{{instance}}]"
    },
    {
     "expr": "jvm_threads_state{state=\"TERMINATED\",instance=\"web3signer.web3signer-gnosis.dappnode:9091\"}",
     "legendFormat": "{{state}} [{{instance}}]"
    }
   ]
  }
 ]
}